### ISSUE TITLE
More robust detection of who should start after a round is won.

### ISSUE THREAD

**Issue by Royten** [benbrunton/pusoy-dos#6]
Currently if somebody gets out and everybody passes, the correct player doesn't start the next round.

Suggest rather than counting passes, the round keep a reference to the last person to play cards.
Probably involves not removing players from the round when they are out but checking number of remaining cards on the players turn and (basically passing) skipping over them if it is 0.
That way, you can check if the current player is the same as the last player to play cards and start a new round either with that player going first, or the next if they have no cards left.

Sound reasonable? Or is there an easier way to do it leaving things mostly as they are?

**Comment by Royten** [comment]
This way would also safe guard against players dropping out/being kicked. (Simply remove all their cards and redistribute, the same logic would ensure turn order didn't go awry).

Though then they could still view the game, so maybe needs extra thought for that scenario.

**Comment by benbrunton** [comment]
For the time being I think you could just reset pass-count to -1 when a player exits.
